name: push-main
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  sync-actions:
    runs-on: [ubuntu-latest]
    steps:
      - uses: khorwood/third-party-actions@actions/checkout/v4
      - name: Sync action branches
        run: |
          ./setup-ssh.sh
          git submodule update --init
          git submodule foreach '$toplevel/sync.sh $sm_path'
        env:
          APP_SSH_KEY: ${{ secrets.APP_SSH_KEY }}
          APP_SSH_USERNAME: git
          OWNER: ${{ github.repository_owner }}
